version: '3.9'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: postgres_ling
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ling_backend_psql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backendtakehome:
    stdin_open: true
    image: backendtakehome
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres-data:
